# Generated by Django 6.0.1 on 2026-01-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_by', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='bookings.screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='bookings.seat')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('screening', 'seat'), name='unique_hold_per_seat_screening')],
            },
        ),
    ]
