# Generated by Django 6.0.1 on 2026-04-03 18:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seathold'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservedseat',
            name='unique_seat_per_screening',
        ),
        migrations.RemoveConstraint(
            model_name='seathold',
            name='unique_hold_per_seat_screening',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_provider',
            field=models.CharField(choices=[('FAKE', 'Fake')], default='FAKE', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_screenings', to='bookings.seat'),
        ),
        migrations.AlterField(
            model_name='seathold',
            name='held_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seathold',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='bookings.seat'),
        ),
        migrations.AddConstraint(
            model_name='reservedseat',
            constraint=models.UniqueConstraint(fields=('screening', 'seat'), name='unique_reserved_seat_per_screening'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.UniqueConstraint(fields=('screening', 'seat'), name='unique_hold_per_screening_seat'),
        ),
        migrations.RemoveField(
            model_name='seathold',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seathold',
            name='updated_at',
        ),
    ]
