# Generated by Django 6.0.1 on 2026-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_reservedseat_unique_seat_per_screening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
